server:
  port: ${SERVER_PORT:25649}
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:subscription-service}
  datasource:
    url: '${DATASOURCE_URL:jdbc:postgresql://postgresql:5432/customer}'
    username: '${DATASOURCE_USERNAME:customer_user01}'
    password: '${DATASOURCE_PASSWORD:customer_user01}'
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600000
      pool-name: SubscriptionJPAHikariCP
      max-lifetime: 360000
      connection-timeout: 5000
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  jpa:
    showSql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE_URL:http://eureka-service:8761/eureka/}          