server:
  port: 25649
spring:
  application:
    name: subscription-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ebill
    username: postgres
    password: samihan123
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600000
      pool-name: SubscriptionJPAHikariCP
      max-lifetime: 360000
      connection-timeout: 5000
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    showSql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#info:
#  app:
#    name: Subscription Service
#    description: Application used to manage customer's subscription
#    version: 1