server:
  port: 25647  
spring:
  application:
    name: bill-service
  datasource:
    url: jdbc:oracle:thin:@//172.18.118.53:1521/duhol02.apd.com.ph
    username: bpx
    password: bpx123
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    showSql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.Oracle12cDialect
management:
  endpoints:
    web:
      exposure:
        include: '*'
#logging:
#  file: /var/lib/app/java/ami/logs/meter.log
#  level:
#    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
#    org.hibernate.type: trace
#    org.hibernate.SQL: DEBUG
#    com.zaxxer.hikari.HikariConfig: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
info:
  app:
    name: Bill Service - UAT
    description: Application used to provide Bill Information coming from CC&B
    version: 1