server:
  port: ${SERVER_PORT:25647}
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:dlpc-bill-retriever}
  datasource:
    url: ${DATASOURCE_URL:jdbc:oracle:thin:@//172.18.118.53:1521/duhol02.apd.com.ph}
    username: ${DATASOURCE_USERNAME:bpx}
    password: ${DATASOURCE_PASSWORD:bpx123}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 5
      maximum-pool-size: 150
      idle-timeout: 600000
      pool-name: PrepaidReaderJPAHikariCP
      max-lifetime: 360000
      connection-timeout: 120000
      leak-detection-threshold: 300000
  jpa:
    showSql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.Oracle12cDialect
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE_URL:http://eureka-service:8761/eureka/}   