server:
  port: 1985
spring:
  application:
    name: kafka-springboot-tutorial
  cloud:
    stream:
      kafka:
        binder:
          brokers: 172.18.13.12:19092,172.18.13.12:29092,172.18.13.12:39092
      bindings:
        stageBill-in-0:
          destination: bill-extracted
          binder: kafka
          group: bill-stager-group
        stageBill-out-0:
          destination: bill-staged
          binder: kafka
        displayStagedBill-in-0:
          destination: bill-staged
          binder: kafka
          group: client-notifier-group
    function:
      definition: stageBill;displayStagedBill
  datasource:
    url: jdbc:oracle:thin:@//172.18.121.147:1521/inhousedblez_uat.apd.com.ph
    username: bpx
    password: bpx
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    showSql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.Oracle12cDialect
management:
  endpoints:
    web:
      exposure:
        include: '*'
#logging:
#  file: /var/lib/app/java/ami/logs/meter.log
#  level:
#    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
#    org.hibernate.type: trace
#    org.hibernate.SQL: DEBUG
#    com.zaxxer.hikari.HikariConfig: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
info:
  app:
    name: Bill Service - UAT
    description: Application used to provide Bill Information coming from CC&B
    version: 1
