spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: ebill-api
        uri: lb://EBILL-API
        predicates:
        - Path=/events/**
      - id: rewrite-dlpc-bill-retriever
        uri: lb://DLPC-BILL-RETRIEVER
        predicates:
        - Path=/dlpc/bills/**
        metadata:
          response-timeout: 20000
          connect-timeout: 20000
        filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/hystrixfallback
        - RewritePath=/dlpc/bills, /bills
      - id: rewrite-veco-bill-retriever
        uri: lb://DLPC-VECO-RETRIEVER
        predicates:
        - Path=/veco/bills/**
        metadata:
          response-timeout: 20000
          connect-timeout: 20000
        filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/hystrixfallback
        - RewritePath=/veco/bills, /bills     
      - id: rewrite-dlpc-subscription-service
        uri: lb://DLPC-SUBSCRIPTION-SERVICE
        predicates:
        - Path=/dlpc/accounts/**
        metadata:
          response-timeout: 20000
          connect-timeout: 20000
        filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/hystrixfallback
        - RewritePath=/dlpc/accounts, /accounts           
server:
  port: 5000
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE_URL:http://eureka-service:8761/eureka/}
  
hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 20000  