server:
  port: 25648
spring:
  application:
    name: bill-stager
  cloud:
    stream:
      kafka:
        binder:
          brokers: 172.18.13.12:19092,172.18.13.12:29092,172.18.13.12:39092
      bindings:
        stageBill-in-0:
          destination: bill-extracted
          binder: kafka
          group: bill-stager-group
        stageBill-out-0:
          destination: bill-staged
          binder: kafka
    function:
      definition: stageBill;displayStagedBill  data:    mongodb:
      host: 172.18.13.12
      port: 27017
      authentication-database: admin
      username: lorauser
      password: 8ZL5#QjS
      database: ebilldb
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#info:
#  app:
#    name: Bill Stager
#    description: Application used to project bill informtaion pulled from CC&B
#    version: 1


service:
  bill:
    url: 
      base: http://localhost:5000/