server:
  port: 25648
spring:
  application:
    name: bill-stager
  cloud:
    stream:
      kafka:
        binder:
          brokers: 172.18.13.12:19092,172.18.13.12:29092,172.18.13.12:39092
      bindings:
        stageBill-in-0:
          destination: bill-extracted
          binder: kafka
          group: bill-stager-group
        stageBill-out-0:
          destination: bill-staged
          binder: kafka
    function:
      definition: stageBill;displayStagedBill  data:    mongodb:
      host: 172.18.13.12
      port: 27017
      authentication-database: admin
      username: lorauser
      password: 8ZL5#QjS
      database: ebilldb
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/  


service:
  bill:
    url: 
      base: ${BILL_SERVICE_BASEURL:http://localhost:5000/}