server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: false
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dlpcdb2
    username: dlpc_customer_user01
    password: dlpc_customer_user01
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600000
      pool-name: SubscriptionJPAHikariCP
      max-lifetime: 360000
      connection-timeout: 5000
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  jpa:
    showSql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  resources:
    cache:
      period: 31536000
      cachecontrol:
        max-age: 31536000
    chain:
      html-application-cache: true
      enabled: true
      strategy:
        content:
          enabled: true
          paths: /webjars/swagger-ui/**.*    
info:
  app:
    name: Subscription Service - DEV
    description: This is the Subscription Service for DLPC
    version: 1      
springdoc:
  swagger-ui.path: /swagger-ui.html
  api-docs.path: /api-docs  